### ISSUE TITLE
Install bugs — `blockList` undefined or null

### ISSUE THREAD

**Issue by nfreear** [nfreear/pomodoro-chrome-ext#7]
...

```
service-worker.js:163 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'findIndex')
    at service-worker.js:163:31
(anonymous) @ service-worker.js:163
service-worker.js:197 SW ~ tabs.onActivated: 1527596305 undefined Array(0)
service-worker.js:197 SW ~ tabs.onActivated: 1527596354 undefined Array(0)
options.js:104 >> options.js
options.js:41 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'join')
    at OptionsStorage.fromStorage (options.js:41:43)
```

**Comment by nfreear** [comment]
Fixed, on 19th August!
